### ISSUE TITLE
How to deal with auth?

### ISSUE THREAD

**Issue by bebraw** [signalfx/swagger-ajax-client#1]
Any idea how to deal with auth? It probably would be enough for me if it was possible to set token at either query or at header (over https of course). Then you would have something like

``` js
var api = swaggerAjaxClient(schema, {
    headers: {
        'X-Auth-Token': 'secrettokengoeshere',
    }, // custom, global headers go here
    // alternative
    query: {
       'token': 'orsecrettokengoeshere'
    } // custom, global query bits go here
})
```

Both `headers` and `query` would be used when performing any query. I can see you can achieve the query case already. Not so sure about headers.

**Comment by unsetbit** [comment]
You can set auth by using `api.auth(token)` or `api.auth(username, password)` when using basic auth.

Auth may be done at any level of the api object (api.auth, or api.resource.auth, or api.resource.operation.auth), but it cannot be done per-request (the auth param is stored for all future requests). You don't have to worry about whether to send the auth via headers or query, since the schema will define that already.

**Comment by bebraw** [comment]
Ok, awesome. Thanks!
